# Generated by Django 2.2 on 2019-04-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='wiki_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='wiki_id',
            field=models.IntegerField(null=True),
        ),
    ]
