# Generated by Django 2.2 on 2019-04-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='wiki_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
