# Generated by Django 2.2 on 2019-04-03 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10, verbose_name='Writers first name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Writers last name')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Article title')),
                ('body', models.CharField(max_length=400, verbose_name='Article body text')),
                ('pub_on', models.DateTimeField(verbose_name='Date this article was published.')),
                ('pub_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Writer')),
            ],
        ),
    ]
