# Generated by Django 2.2 on 2019-04-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WikiModel',
        ),
    ]
