# Generated by Django 2.2 on 2019-04-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='wiki_id',
            field=models.IntegerField(default=None, editable=False, null=True),
        ),
    ]
