# Generated by Django 2.2 on 2019-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='wiki_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='wiki_id',
            field=models.IntegerField(null=True),
        ),
    ]
